# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
right_format = """
[](color_bg1)\
$kubernetes\
[](fg:color_bg1 bg:color_bg2)\
$time
"""

format = """
[](blue)\
$sudo\
(fg:blue bg:color_bg1)\
$directory\
[](fg:color_bg1 bg:color_bg2)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
[](fg:color_bg2 bg:color_green)\
$deno\
$dotnet\
$golang\
$gradle\
$helm\
$java\
$kotlin\
$lua\
$nodejs\
$python\
$rust\
$scala\
$terraform\
$nix_shell\
$conda\
[](fg:color_green bg:blue)\
$docker_context\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
[](blue)\
$jobs\
$battery\
$status\
$cmd_duration\
$container\
$shell\
$line_break\
$character"""

palette = 'mine'

[palettes.mine]
color_fg0 = '#fbf1c7'
color_fg1 = '#9A348E'
color_bg1 = '#33658A'
color_bg2 = '#5578AD'
color_bg3 = '#779ACE'
color_aqua = '#689d6a'
color_green = '#006064'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#E040FB'
color_yellow = '#d79921'
color_cyan = '#00BFA5'


[character]
success_symbol = '[↳](bold green)'
error_symbol = '[✗](bold red) '

[time]
disabled = false
style = "bg:color_bg2 fg:color_fg0"
format = '[ $time ]($style)'

[kubernetes]
disabled = false
style = "bg:color_bg1"
format = '[$symbol$context( \($namespace\))]($style)'

[cmd_duration]
min_time = 5000
format = '\[[⏱ $duration]($style)\]'

[directory]
style = "bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "… /"

[docker_context]
symbol = "  "
format = ' [$symbol$context]($style)'

[gcloud]
symbol = "  "
format = '[$symbol$account(@$domain)(\($region\))]($style)'

[git_branch]
style = "bg:color_bg2"
symbol = "  "
format = '[$symbol$branch ]($style)'

[git_commit]
style = "bg:color_bg2"
tag_symbol = '  '
format = '([\($hash$tag\)]($style))'

[git_status]
style = "bg:color_bg2 fg:color_fg0 bold"
ahead = '󱦲${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '󱦳${count}'
deleted = '🗑'
stashed = '📦'
format = '([\[$all_status $ahead_behind\]]($style))'

[golang]
symbol = "  "
style = "bg:color_green"
format = '[$symbol($version)]($style)'

[java]
symbol = "  "
style = "bg:color_green"
format = '[$symbol($version)]($style)'

[kotlin]
symbol = "  "
style = "bg:color_green"
format = '[$symbol($version)]($style)'

[lua]
symbol = "  "
style = "bg:color_green"
format = '[$symbol($version)]($style)'

[nodejs]
symbol = "  "
style = "bg:color_green"
format = '[$symbol($version)]($style)'

[python]
symbol = "  "
style = "bg:color_green"
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[rust]
symbol = " 󱘗 "
style = "bg:color_green"
format = '[$symbol($version)]($style)'

[sudo]
disabled = false
style = "bg:blue"
symbol = "🧙 "
format = "[$symbol]($style)"

[scala]
symbol = "  "
style = "bg:color_green"
format = '[$symbol($version)]($style)'

[gradle]
symbol = "  "
style = "bg:color_green"
format = '[$symbol($version)]($style)'

######## Disable

[aws]
disabled = true

[package]
disabled = true
